### ISSUE TITLE
How to lunch the stack ?

### ISSUE THREAD

**Issue by jerome-morgado** [giusedroid/aws-serverless-monitoring#24]
How to start the stack ?
``make`` ?

**Comment by giusedroid** [comment]
Hey sorry it took me a long time to reply!
This repo was thought to illustrate how to deploy the stack via circle-ci.
If you want to do it from your local machine I suggest you setup your environment as described [here](https://github.com/giusedroid/aws-serverless-monitoring#environment) then execute the following

```
make security
make backend-local
make dns-aurora
make grafana-local
make dns-grafana
```

you can have more info about the deployment logic [here](https://github.com/giusedroid/aws-serverless-monitoring/blob/master/.circleci/config.yml)
